spring:
  datasource:
    url: jdbc:mysql://118.113.201.253:8805/store
    username: root
    password: Hj_1987121
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: DatebookHikariCP
      idle-timeout: 30000 #最大空闲时间,30000秒内未使用则连接被丢弃。若为0则永不丢弃。Default: 0
      auto-commi: true #连接关闭时默认将所有未提交的操作回滚。Default: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8090
  servlet:
    context-path: /MeiYe
jwt:
  configuration:
    secret: MeiYe_York
    time-out: 1800000000
    token-in-header: token
    valid-token-start-with: Bearer;


  mybatis:
    type-aliases-package: com.meiye.bo