spring:
  datasource:
    url: jdbc:mysql://192.168.31.171:8805/store
    username: root
    password: Hj_1987121
    driver-class-name: com.mysql.jdbc.Driver
    validation-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html


server:
  port: 8080
  servlet:
    context-path: /MeiYe
