spring:
  datasource:
    url: jdbc:mysql://192.168.31.171:8805/store
    username: root
    password: Hj_1987121
    driver-class-name: com.mysql.jdbc.Driver
    validation-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true